Feat/activity subscription
Kevinmsouza/Drivent-back pull request #10
Opened 2022-01-29 19:21 UTC by pedrohotz

2022-01-29 20:14 UTC, Kevinmsouza requested changes
Bem legal a logica que você usou, deixei apenas alguns comentarios em detalhes que passaram despercebidos no refactor.

2022-01-29 20:14 UTC, Kevinmsouza commented on src/entities/Ticket.ts
> +import { BaseEntity, Entity, PrimaryGeneratedColumn, Column, OneToOne, ManyToOne, JoinColumn, OneToMany, ManyToMany, JoinTable } from "typeorm";
OneToMany não está sendo utilizado.
```suggestion
import { BaseEntity, Entity, PrimaryGeneratedColumn, Column, OneToOne, ManyToOne, JoinColumn, ManyToMany, JoinTable } from "typeorm";
```

2022-01-29 20:14 UTC, Kevinmsouza commented on src/entities/Activity.ts
> +      });
Sobre o filter:
> Função é um predicado, para testar cada elemento do array. Retorna true para manter o elemento, false caso contrário, recebendo três argumentos:

Embora provavelmente funcione desse jeito, fica bem fora de semantica utilizar truthy/falsy como retorno do filter.
```suggestion
      const userActivities = AllActivities.filter((act) => act.Date.id === activity.Date.id);
```

2022-01-30 01:24 UTC, patricia270 approved these changes

2022-01-30 14:10 UTC, Kevinmsouza approved these changes

2022-01-30 14:10 UTC, merged